FROM node:23 AS builder

WORKDIR /app

COPY backend/app/package*.json ./
RUN npm ci

COPY backend/app ./
COPY shared shared/

RUN npm run build


FROM node:23 AS runtime

WORKDIR /app

COPY backend/app/package*.json ./
RUN npm ci --production

COPY --from=builder /app/build ./build
COPY --from=builder /app/uploads ./uploads
COPY --from=builder /app/shared ./shared

EXPOSE 3001

CMD ["node", "build/server.cjs"]
