{
 "title": "Alerts dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alerts on HighContainerCPU",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"HighContainerCPU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts on HighContainerMemory firing",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"HighContainerMemory\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Alerts on HighContainerSwap firing",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"HighContainerSwap\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}