{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container_name",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container start time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (container_start_time_seconds{name=~\"$container_name\"}) * 1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (1 - avg by (instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])))"
      }
     ]
    },
    {
     "title": "RAM used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_min((1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100, 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SWAP used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes)) * 100"
      }
     ]
    },
    {
     "title": "CPU cores",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total) by (cpu))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_MemTotal_bytes" }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_SwapTotal_bytes" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
       "legendFormat": "Busy user"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
       "legendFormat": "Busy other"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" },
      {
       "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes",
       "legendFormat": "Cache + Buffer"
      },
      { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
      {
       "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
       "legendFormat": "Swap used"
      }
     ]
    },
    {
     "title": "Network traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total[$__rate_interval])*8",
       "legendFormat": "Received {{device}}"
      },
      {
       "expr": "-rate(node_network_transmit_bytes_total[$__rate_interval])*8",
       "legendFormat": "Transmitted {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * max by(name) (rate(container_cpu_usage_seconds_total{name=~\"$container_name\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{mode=\"idle\"}) by (cpu)))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Containers CPU %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * max by(name) (rate(container_cpu_usage_seconds_total{name=~\"$container_name\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{mode=\"idle\"}) by (cpu)))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Containers cpu usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_usage_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Containers cpu user",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_user_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Containers cpu system",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_system_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM Used",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * max by(name) (container_memory_usage_bytes{name=~\"$container_name\"})/scalar(node_memory_MemTotal_bytes)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Containers memory usage bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_usage_bytes{name=~\"$container_name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Swap used",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 240 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * max by(name) (container_memory_swap{name=~\"$container_name\"})/scalar(node_memory_SwapTotal_bytes)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Containers memory swap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 240 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_swap{name=~\"$container_name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers received bytes & Containers transmitted bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 401 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_network_receive_bytes_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} received"
      },
      {
       "expr": "- max by (name) (rate(container_network_transmit_bytes_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} transmitted"
      }
     ]
    },
    {
     "title": "Containers received packets & Containers transmitted packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 401 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_network_receive_packets_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} received"
      },
      {
       "expr": "- max by (name) (rate(container_network_transmit_packets_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} transmitted"
      }
     ]
    },
    {
     "title": "Containers packets dropped while received &  Containers packets dropped while transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 481 },
     "targets": [
      {
       "expr": "max by (name) (rate(container_network_receive_packets_dropped_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} received"
      },
      {
       "expr": "- max by (name) (rate(container_network_transmit_packets_dropped_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} transmitted"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers fs usage",
     "type": "timeseries",
     "description": "Cumulative count of containers fs usage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 364 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_usage_bytes{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk usage %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 364 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * max by(name) (container_fs_usage_bytes{name=~\"$container_name\"}) / max by(name) (container_fs_limit_bytes{name=~\"$container_name\"})\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Containers fs read & fs write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 372 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_read_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} read"
      },
      {
       "expr": "max by (name) (-rate(container_fs_write_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} write"
      }
     ]
    },
    {
     "title": "Containers fs io",
     "type": "timeseries",
     "description": "Cumulative count of containers io",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 372 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_io_time_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (name) (rate(container_fs_io_time_weighted_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} weighed"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 365 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(nginx_http_requests_total[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 365 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "nginx_connections_active", "legendFormat": "{{instance}} active" },
      { "expr": "nginx_connections_reading", "legendFormat": "{{instance}} reading" },
      { "expr": "nginx_connections_waiting", "legendFormat": "{{instance}} waiting" },
      { "expr": "nginx_connections_writing", "legendFormat": "{{instance}} writing" }
     ]
    }
   ]
  },
  {
   "title": "Container $container_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "container_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Container cpu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 428 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_system_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} system"
      },
      {
       "expr": "max by (name) (rate(container_cpu_user_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} user"
      },
      {
       "expr": "max by (name) (rate(container_cpu_usage_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} usage"
      }
     ]
    },
    {
     "title": "Container memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 436 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_usage_bytes{name=~\"$container_name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Container memory swap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 436 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_swap{name=~\"$container_name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Container received bytes & container transmitted bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 444 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_network_receive_bytes_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} received"
      },
      {
       "expr": "- max by (name) (rate(container_network_transmit_bytes_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} transmitted"
      }
     ]
    },
    {
     "title": "Container packets received & packets transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 444 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_network_receive_packets_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} received"
      },
      {
       "expr": "- max by (name) (rate(container_network_transmit_packets_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} transmitted"
      }
     ]
    },
    {
     "title": "Container packets dropped (received & transmitted)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 444 },
     "targets": [
      {
       "expr": "max by (name) (rate(container_network_receive_packets_dropped_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} received"
      },
      {
       "expr": "- max by (name) (rate(container_network_transmit_packets_dropped_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} transmitted"
      }
     ]
    },
    {
     "title": "Container fs read & write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 452 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_read_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} read"
      },
      {
       "expr": "max by (name) (-rate(container_fs_write_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} write"
      }
     ]
    },
    {
     "title": "Container fs usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 452 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_usage_bytes{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Container fs io",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 452 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_io_time_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (name) (rate(container_fs_io_time_weighted_seconds_total{name=~\"$container_name\"}[$__rate_interval]))",
       "legendFormat": "{{name}} weighed"
      }
     ]
    }
   ]
  }
 ]
}